version: '3.9'
services:
  db:
    platform: linux/x86_64
    image: postgres:latest
    container_name: pg-container
    env_file:
      .env
    restart: 'always'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: NG-test-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      .env
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
      start_period: 15s
    ports:
      - "3001:3001"
    volumes:
      - './backend/src:/app/src'